# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aceDLNMopt <- function(R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, verbose) {
    .Call(`_aceDLNM_aceDLNMopt`, R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, verbose)
}

aceDLNMCI <- function(R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, Rci, rseed, ifeta, delta, verbose) {
    .Call(`_aceDLNM_aceDLNMCI`, R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, Rci, rseed, ifeta, delta, verbose)
}

ConditionalAIC <- function(R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing) {
    .Call(`_aceDLNM_ConditionalAIC`, R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing)
}

aceDLNMopt_nosmooth <- function(R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xfix, R_Zf, R_Xoffset, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaF, verbose) {
    .Call(`_aceDLNM_aceDLNMopt_nosmooth`, R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xfix, R_Zf, R_Xoffset, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaF, verbose)
}

aceDLNMCI_nosmooth <- function(R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xfix, R_Zf, R_Xoffset, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaF, Rci, rseed, ifeta, delta, verbose) {
    .Call(`_aceDLNM_aceDLNMCI_nosmooth`, R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xfix, R_Zf, R_Xoffset, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaF, Rci, rseed, ifeta, delta, verbose)
}

ConditionalAIC_nosmooth <- function(R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xfix, R_Zf, R_Xoffset, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaF) {
    .Call(`_aceDLNM_ConditionalAIC_nosmooth`, R_y, R_B_inner, R_knots_f, R_Sw, R_Sf, R_Dw, R_Xfix, R_Zf, R_Xoffset, R_alpha_f, R_phi, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaF)
}

knotindex <- function(x, t) {
    .Call(`_aceDLNM_knotindex`, x, t)
}

Bspline <- function(x, j, t, p) {
    .Call(`_aceDLNM_Bspline`, x, j, t, p)
}

Bsplinevec <- function(x, t, p) {
    .Call(`_aceDLNM_Bsplinevec`, x, t, p)
}

BsplinevecCon <- function(x, t, p, Z) {
    .Call(`_aceDLNM_BsplinevecCon`, x, t, p, Z)
}

BsplinevecConJ <- function(x, t, p, Z, j) {
    .Call(`_aceDLNM_BsplinevecConJ`, x, t, p, Z, j)
}

Bsplinevec2 <- function(x, t, p) {
    .Call(`_aceDLNM_Bsplinevec2`, x, t, p)
}

Bsplinevec2Con <- function(x, t, p, Z) {
    .Call(`_aceDLNM_Bsplinevec2Con`, x, t, p, Z)
}

Bsplinevec2ConJ <- function(x, t, p, Z, j) {
    .Call(`_aceDLNM_Bsplinevec2ConJ`, x, t, p, Z, j)
}

BsplinevecFill <- function(x, t, p, col, Gx) {
    invisible(.Call(`_aceDLNM_BsplinevecFill`, x, t, p, col, Gx))
}

Bsplinevec2Fill <- function(x, t, p, col, Gx) {
    invisible(.Call(`_aceDLNM_Bsplinevec2Fill`, x, t, p, col, Gx))
}

Integral <- function(knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD) {
    .Call(`_aceDLNM_Integral`, knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD)
}

deBoor <- function(x, t, beta, p) {
    .Call(`_aceDLNM_deBoor`, x, t, beta, p)
}

Integral_interpolate <- function(knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD) {
    .Call(`_aceDLNM_Integral_interpolate`, knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD)
}

Interpolate <- function(X, y) {
    .Call(`_aceDLNM_Interpolate`, X, y)
}

